services:

  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ecommerce_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: ecommerce_web
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:root@db:5432/ecommerce_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your_super_secret_key_change_this
      - REFRESH_SECRET_KEY=your_refresh_secret_key_change_this
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    container_name: ecommerce_worker
    command: celery -A ecommerce_api.celery_app.celery_app worker --loglevel=info
    volumes:
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:root@db:5432/ecommerce_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY=your_super_secret_key_change_this
      - REFRESH_SECRET_KEY=your_refresh_secret_key_change_this
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
